### ISSUE TITLE
add label to mark

### ISSUE THREAD

**Issue by bheadwhite** [norbertK/taskmarks#20]
it would be nice if you could add a label to a mark.

for example.
when creating a new mark, 
have an input that will pop up to prompt a user to associate a label with that mark, 
that label will be what is shown in the list of marks.

this will allow you to filter/search the list for labels, rather than searching/filtering line numbers (current way)

**Comment by norbertK** [comment]
just working on that, but it breaks taskmarks.json (need a place to save label)
<img width="554" alt="image" src="https://user-images.githubusercontent.com/926000/164502043-6d5c576b-c1d0-4402-ac38-3163268178d3.png">

**Comment by bheadwhite** [comment]
right, i would change line 13 and call those `marks`. 

would we want to support backwards compatibility?

**Comment by norbertK** [comment]
but for now: no backwards compatibility

**Comment by norbertK** [comment]
ok - very untested
enable labels:
<img width="157" alt="image" src="https://user-images.githubusercontent.com/926000/164519091-8d9fdcfe-063d-4b79-86c9-d47ff03543d1.png">

for now restart vscode, then, after toggle bookmark

<img width="285" alt="image" src="https://user-images.githubusercontent.com/926000/164538978-ea80b8f1-f73e-44fc-a861-b02a194a2d10.png">

**Comment by bheadwhite** [comment]
Awesome. I’ll be playing with it within the hour or so

**Comment by bheadwhite** [comment]
Error in taskmarks output log `Cannot read properties of undefined (reading
'length')`

**Comment by norbertK** [comment]
I only got an error, when I start code with an old version of taskmarks.json
new version detects and removes (0.8.27)

**Comment by bheadwhite** [comment]
That build works for me!

Awesome. I think this is a step in the right direction.

The mark labels are still not searchable tho. The line numbers are what get
filtered out in the list view.

**Comment by norbertK** [comment]
sorry, thought I'd changed that  (0.8.29)
<img width="197" alt="image" src="https://user-images.githubusercontent.com/926000/164968526-9e6e3fde-d1c3-4047-867e-ed68f7db21d5.png">
<img width="211" alt="image" src="https://user-images.githubusercontent.com/926000/164968558-ee2567b1-3e88-42a8-8f95-6c8dd544067b.png">

**Comment by bheadwhite** [comment]
found something that was giving me some buggy behavior.

when calling `showLine` in the `Decorator` module, if the line is `NaN` then something unexpected happens on my side.

if you could add checking for that case in the return early checks, that would fix it

**Comment by norbertK** [comment]
0.8.31

**Comment by norbertK** [comment]
any idea when that happens?

**Comment by bheadwhite** [comment]
When a user is using labels instead of line numbers as marks.

**Comment by bheadwhite** [comment]
```    if (
      activeTextEditor === null ||
      activeTextEditor === undefined ||
      Number.isNaN(lineNumber)
    ) {
      return;
    }

**Comment by norbertK** [comment]
sorry, did not think that through
and I thought I tried it???
0.8.33

**Comment by norbertK** [comment]
does it work, or do you still have problems?

**Comment by bheadwhite** [comment]
It is working as expected without any bugs As far as I can tell. Great job
and sorry for not reporting sooner!
