### ISSUE TITLE
rename bookmarks

### ISSUE THREAD

**Issue by bheadwhite** [norbertK/taskmarks#5]
<img width="120" alt="CleanShot 2021-12-30 at 12 58 09@2x" src="https://user-images.githubusercontent.com/26074150/147784255-980f74ec-9149-4b2c-88e8-8cecc55b7e4e.png">

this is a great tool, can we implement a way to rename the bookmarks to something custom?

navigating through a list of bookmarks is a little hard visually, if we could flag each one with a label this would help.

**Comment by norbertK** [comment]
sorry - new job, no time
did you implement this in your fork?
I'll try to merge your fork into taskmarks

**Comment by bheadwhite** [comment]
no. this hasnt been implemented yet in my fork.

i have not been  using this extension as much recently because its not
consistent in looking up the marks (often times, the marks do not exist
when trying to access them via the list command).

i have not looked into how this happens yet but i'd love to find out so i
can keep using it.

**Comment by norbertK** [comment]
I have created a pre release version 0.8.21 that fixes most (probably not all  :-(  ) errors and I've implemented a way to rename a task - just noticed, that's not what you wanted
could you have a look, and tell me what you think
any errors I overlooked?

**Comment by bheadwhite** [comment]
[image: CleanShot 2022-04-20 at ***@***.***
getting this error.

**Comment by norbertK** [comment]
hm - can you tell me, when that happened?
<img width="613" alt="image" src="https://user-images.githubusercontent.com/926000/164388613-08023952-60d0-44fa-bc63-850627bba23f.png">
is there anything in 'Taskmarks Errrors'
works fine on my two PCs (Win 10 and Win 11)

**Comment by norbertK** [comment]
and Version is v0.8.21?
<img width="296" alt="image" src="https://user-images.githubusercontent.com/926000/164389780-737eb4d5-1ef7-43b8-8e3d-41eab43e7129.png">

**Comment by bheadwhite** [comment]
i was on what was available as the pre-release build in vscode. (8.17 i
think)

I downloaded the source code and built local vsix and it works.

i'll try this build out, hoping that it is more reliable through persisting
issues
(sometimes when i run taskmarks.selectMarkFromList some of my marks will be
missing from the list)

**Comment by norbertK** [comment]
sorry
when I wrote my request to you, I already had published v0.8.21, but I had forgotten, to push my latest changes to github
could you try again?

**Comment by bheadwhite** [comment]
im running the build from the latest git commit [c7416ae](https://github.com/norbertK/taskmarks/commit/c7416ae6474048b79e262e12a8b1565f991413d4)

**Comment by norbertK** [comment]
and you still have missing marks - checking now

**Comment by bheadwhite** [comment]
It only happens *sometimes* it’s hard for me to reproduce but in using this
extension in my work monorepo (it’s pretty big but I don’t think that
matters), sometimes after switching contexts, some marks will be missing in
the list.

**Comment by norbertK** [comment]
can't reproduce that - had an idea, but that was wrong 
sorry

**Comment by bheadwhite** [comment]
the original issue opened here will be carried on in #20
